# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Nov 30 20:37:49 2022
# ------------------------------------------------

package:
  name: _ipython_minor_entry_point
  version: 8.7.0
source:
  fn: LICENSE_ipython_8.7.0
  sha256: e0e390748ed440ab893ca1f135a88a920aaf5409dbb90a5b427c75c5e51268fb
  url: https://raw.githubusercontent.com/ipython/ipython/8.7.0/LICENSE
build:
  entry_points:
    - ipython3.9 = IPython:start_ipython
  noarch: python
  number: '0'
  string: h8cf3c4a_0
requirements:
  build: []
  run:
    - python ==3.9.*
  run_constrained:
    - ipython ==8.7.0.*
test:
  commands:
    - pip check
    - which ipython3.9
  requires:
    - pip
about:
  home: https://github.com/ipython/ipython
  license: BSD-3-Clause
  license_file: LICENSE_ipython_8.7.0
  summary: A console script for starting IPython with a specific python major/minor
    version
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - conda-forge/ipython
